/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApkJARAN.view;

import ApkJARAN.controller.InputController;
import ApkJARAN.view.LoginForm.Session;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

import java.awt.event.*;
import java.util.regex.Pattern;



/**
 *
 * @author Silvio
 */
public class InputForm extends javax.swing.JFrame {
    private InputController controller;
    
    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
        controller = new InputController();

        // Set kolom tabel hanya sekali
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Pelapor", "Alamat", "Kebutuhan", "Jumlah KK", "No Telp", "Keparahan", "Status", "Tanggal", "ID"
            }
        );
        Table.setModel(model);

        // Sembunyikan kolom ID (kolom ke-8 = index 7)
        Table.getColumnModel().getColumn(8).setMinWidth(0);
        Table.getColumnModel().getColumn(8).setMaxWidth(0);
        Table.getColumnModel().getColumn(8).setWidth(0);

        tampilkanDataKeTabel();  // Panggil setelah semuanya di-setup
        setTableFilter();        // Set filter terakhir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        pelaporLabel = new javax.swing.JLabel();
        kebutuhanLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        kebutuhan = new javax.swing.JComboBox<>();
        alamat = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        statusLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();
        pelapor = new javax.swing.JComboBox<>();
        totalKKLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        noTelp = new javax.swing.JTextField();
        totalKK = new javax.swing.JTextField();
        toBantuanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pelapor", "Alamat", "Kebutuhan Khusus", "Jumlah KK", "No. Telp", "Tingkat Keparahan", "Status", "Tanggal"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        pelaporLabel.setText("Pelapor");

        kebutuhanLabel.setText("Kebutuhan Khusus:");

        alamatLabel.setText("Alamat");

        kebutuhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Yes", "No" }));
        kebutuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebutuhanActionPerformed(evt);
            }
        });

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        batalBtn.setText("Batal");
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Belum Ditangani", "Sudah Ditangani", "Evakuasi" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        statusLabel.setText("Status");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        pelapor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Warga", "RT/ RW", "Lainnya", " " }));
        pelapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelaporActionPerformed(evt);
            }
        });

        totalKKLabel.setText("Jumlah KK");

        noTelpLabel.setText("No. Telp");

        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });

        totalKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalKKActionPerformed(evt);
            }
        });

        toBantuanBtn.setText("Daftar Bantuan");
        toBantuanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBantuanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(pelaporLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pelapor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalKKLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(noTelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalKK, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(noTelp)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kebutuhanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(logoutBtn)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(toBantuanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hapusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tambahBtn))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(editBtn))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(batalBtn)))))
                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(totalKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(noTelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pelaporLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalKKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kebutuhanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahBtn)
                            .addComponent(editBtn))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusBtn)
                            .addComponent(batalBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toBantuanBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilkanDataKeTabel() {
        var data = controller.ambilSemuaData();
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0); // Clear baris lama

        for (Object[] row : data) {
            model.addRow(row); // Tambahkan baris baru
        }
    }
    
    

    private TableRowSorter<DefaultTableModel> sorter;
    private void setTableFilter() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        sorter = new TableRowSorter<>(model);
        Table.setRowSorter(sorter);

        searchField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { search(); }
            public void removeUpdate(DocumentEvent e) { search(); }
            public void changedUpdate(DocumentEvent e) { search(); }

            public void search() {
                String keyword = searchField.getText().trim();
                if (keyword.length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(keyword)));
                }
            }
        });
        
    }

    
    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void kebutuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebutuhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebutuhanActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        int selectedRow = Table.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(Table.getModel().getValueAt(selectedRow, 8).toString());
                boolean success = controller.hapusData(id);
                if (success) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus ya");
                    tampilkanDataKeTabel();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dulu baris yang mau dihapus ya");
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        pelapor.setSelectedIndex(0);
        alamat.setText("");
        kebutuhan.setSelectedIndex(0);
        status.setSelectedIndex(0);
        totalKK.setText("");
        noTelp.setText("");
    }//GEN-LAST:event_batalBtnActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        if (pelapor.getSelectedItem().equals("Pilih...") || alamat.getText().isEmpty()
        || kebutuhan.getSelectedItem().equals("Pilih...") || status.getSelectedItem().equals("Pilih...")
        || totalKK.getText().isEmpty() || noTelp.getText().isEmpty()) {

        JOptionPane.showMessageDialog(null, "Semua kolom harus diisi dulu ya", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (!totalKK.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Jumlah KK harus berupa angka ya", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (!noTelp.getText().matches("\\d+") || !noTelp.getText().startsWith("62") || !noTelp.getText().matches("^62\\d{8,12}$")) {
            JOptionPane.showMessageDialog(null, "Nomor telepon Harus Berupa Angka, dimulai dengan 62, dan berjumlah 10-14 angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }else {
            String nama = (String) pelapor.getSelectedItem();
            String almt = alamat.getText();
            String kebutuhanKhusus = (String) kebutuhan.getSelectedItem();
            String sts = (String) status.getSelectedItem();
            String jumlahKK = totalKK.getText();
            String noTelpon = noTelp.getText();

            boolean berhasil = controller.simpanData(nama, almt, kebutuhanKhusus, sts, jumlahKK, noTelpon, Session.loggedInUsername);
            if (berhasil) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                pelapor.setSelectedIndex(0);
                alamat.setText("");
                kebutuhan.setSelectedIndex(0);
                status.setSelectedIndex(0);
                totalKK.setText("");
                noTelp.setText("");

                tampilkanDataKeTabel(); // Refresh tabel
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data, coba lagi ya", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int selectedRow = Table.getSelectedRow();
        
        if (pelapor.getSelectedItem().equals("Pilih...") || alamat.getText().isEmpty()
            || kebutuhan.getSelectedItem().equals("Pilih...") || status.getSelectedItem().equals("Pilih...")
            || totalKK.getText().isEmpty() || noTelp.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi dulu yaa", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else if (!totalKK.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Jumlah KK harus berupa angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }else if (!noTelp.getText().matches("\\d+") || !noTelp.getText().startsWith("62") || !noTelp.getText().matches("^62\\d{8,12}$")) {
            JOptionPane.showMessageDialog(null, "Nomor telepon Harus Berupa Angka, dimulai dengan 62, dan berjumlah 10-14 angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }else {
            if (selectedRow != -1) {
                int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin Mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    DefaultTableModel model = (DefaultTableModel) Table.getModel();

                    // Langsung ambil ID dari model, bukan dari tampilan kolom (bisa disembunyikan)
                    Object idObj = model.getValueAt(selectedRow, model.getColumnCount() - 1); // ID di posisi terakhir
                    int id = Integer.parseInt(idObj.toString());

                    String nama = (String) pelapor.getSelectedItem();
                    String almt = alamat.getText();
                    String kebutuhanKhusus = (String) kebutuhan.getSelectedItem();
                    String sts = (String) status.getSelectedItem();
                    String jumlahKK = totalKK.getText();
                    String noTelpon = noTelp.getText();

                    boolean berhasil = controller.updateData(id, nama, almt, kebutuhanKhusus, sts, jumlahKK, noTelpon);
                    if (berhasil) {
                        JOptionPane.showMessageDialog(this, "Data berhasil diedit");
                        tampilkanDataKeTabel();
                    } else {
                        JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    // Reset form input
                    pelapor.setSelectedIndex(0);
                    alamat.setText("");
                    kebutuhan.setSelectedIndex(0);
                    status.setSelectedIndex(0);
                    totalKK.setText("");
                    noTelp.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih dulu baris yang mau diedit ya");
            }
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int selectedRow = Table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        pelapor.setSelectedItem(model.getValueAt(selectedRow, 0));
        alamat.setText(model.getValueAt(selectedRow, 1).toString());
        kebutuhan.setSelectedItem(model.getValueAt(selectedRow, 2));
        totalKK.setText(model.getValueAt(selectedRow, 3).toString());
        noTelp.setText(model.getValueAt(selectedRow, 4).toString());
        status.setSelectedItem(model.getValueAt(selectedRow, 6));
    }//GEN-LAST:event_TableMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void pelaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelaporActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void totalKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKKActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void toBantuanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBantuanBtnActionPerformed
        new BantuanForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toBantuanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JButton batalBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kebutuhan;
    private javax.swing.JLabel kebutuhanLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField noTelp;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JComboBox<String> pelapor;
    private javax.swing.JLabel pelaporLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton toBantuanBtn;
    private javax.swing.JTextField totalKK;
    private javax.swing.JLabel totalKKLabel;
    // End of variables declaration//GEN-END:variables

}
