/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApkJARAN.view;

import ApkJARAN.controller.PelaporController;
import ApkJARAN.view.LoginForm.Session;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 *
 * @author Silvio
 */
public class PelaporForm extends javax.swing.JFrame {
    PelaporController controller;
    /**
     * Creates new form UserDashboard
     */
    public PelaporForm() {
        initComponents();
        try {
            controller = new PelaporController();
            tampilkanDataKeTabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal konek controller: " + e.getMessage());
        }

        // Sembunyikan scrollpane (tabel) saat pertama kali tampil
        jScrollPane1.setVisible(false); // <- Tambahan penting ini yaa

        resultCheck.addActionListener(evt -> {
            jScrollPane1.setVisible(resultCheck.isSelected());
            revalidate();
            repaint();
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        logoutBtn = new javax.swing.JButton();
        pelaporLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        kebutuhanLabel = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        kebutuhan = new javax.swing.JComboBox<>();
        kirimBtn = new javax.swing.JButton();
        totalKKLabel = new javax.swing.JLabel();
        totalKK = new javax.swing.JTextField();
        noTelpLabel = new javax.swing.JLabel();
        pelapor = new javax.swing.JComboBox<>();
        noTelp = new javax.swing.JTextField();
        resultCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        pelaporLabel.setText("Pelapor");

        alamatLabel.setText("Alamat");

        kebutuhanLabel.setText("Kebutuhan Khusus:");

        kebutuhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Yes", "No" }));

        kirimBtn.setText("Kirim");
        kirimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimBtnActionPerformed(evt);
            }
        });

        totalKKLabel.setText("Jumlah KK");

        totalKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalKKActionPerformed(evt);
            }
        });

        noTelpLabel.setText("No. Telp");

        pelapor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Warga", "RT/ RW", "Lainnya", " " }));

        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });

        resultCheck.setText("Result");
        resultCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultCheckActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pelapor", "Alamat", "Kebutuhan Khusus", "Jumlah KK", "No. Telp", "Status", "Date"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kebutuhanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kirimBtn)
                            .addComponent(kebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pelaporLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pelapor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalKKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noTelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalKK, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(totalKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalKKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(noTelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(19, 19, 19)))
                        .addComponent(kebutuhanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pelaporLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(kirimBtn)
                .addGap(32, 32, 32)
                .addComponent(resultCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void tampilkanDataKeTabel() {
        try {
            ArrayList<String[]> data = controller.getDataPelapor(Session.loggedInUsername);
            DefaultTableModel model = new DefaultTableModel(new String[]{
                "Pelapor", "Alamat", "Kebutuhan Khusus", "Jumlah KK", "No. Telp", "Status", "Tanggal", "ID"
            }, 0);


            for (String[] row : data) {
                model.addRow(row);
            }

            Table.setModel(model);
            Table.getColumnModel().getColumn(7).setMinWidth(0);
            Table.getColumnModel().getColumn(7).setMaxWidth(0);
            Table.getColumnModel().getColumn(7).setWidth(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error tampilkan data: " + e.getMessage());
        }
    }

    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void totalKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKKActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void kirimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimBtnActionPerformed
        String tipePelapor = pelapor.getSelectedItem().toString();
        String almt = alamat.getText();
        String kebutuhanKhusus = kebutuhan.getSelectedItem().toString();
        String jumlahKKStr = totalKK.getText();
        String telp = noTelp.getText();

        if (tipePelapor.equals("Pilih...") || almt.isEmpty() || kebutuhanKhusus.equals("Pilih...") || jumlahKKStr.isEmpty() || telp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi semua kolom dulu ya");
            return;
        }

        if (!jumlahKKStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Jumlah KK harus angka");
            return;
        }

        else if (!telp.matches("\\d+") || !telp.startsWith("62") || !telp.matches("^62\\d{8,12}$")) {
            JOptionPane.showMessageDialog(null, "Nomor telepon Harus Berupa Angka, dimulai dengan 62, dan berjumlah 10-14 angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Kamu Sudah Yakin Dengan Laporanmu?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                controller.kirimPelapor(tipePelapor, almt, kebutuhanKhusus, Integer.parseInt(jumlahKKStr), telp, Session.loggedInUsername);
                JOptionPane.showMessageDialog(this, "Data berhasil dikirim");

                // reset form
                pelapor.setSelectedIndex(0);
                alamat.setText("");
                kebutuhan.setSelectedIndex(0);
                totalKK.setText("");
                noTelp.setText("");

                tampilkanDataKeTabel();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal kirim data: " + e.getMessage());
        }
    }//GEN-LAST:event_kirimBtnActionPerformed

    private void resultCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultCheckActionPerformed
        
    }//GEN-LAST:event_resultCheckActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int selectedRow = Table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        pelapor.setSelectedItem(model.getValueAt(selectedRow, 0));
        alamat.setText(model.getValueAt(selectedRow, 1).toString());
        kebutuhan.setSelectedItem(model.getValueAt(selectedRow, 2));
        totalKK.setText(model.getValueAt(selectedRow, 3).toString());
        noTelp.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_TableMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelaporForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelaporForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelaporForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelaporForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelaporForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> kebutuhan;
    private javax.swing.JLabel kebutuhanLabel;
    private javax.swing.JButton kirimBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField noTelp;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JComboBox<String> pelapor;
    private javax.swing.JLabel pelaporLabel;
    private javax.swing.JCheckBox resultCheck;
    private javax.swing.JTextField totalKK;
    private javax.swing.JLabel totalKKLabel;
    // End of variables declaration//GEN-END:variables
}
